name: Build CIA

# Controls when the workflow will run
on:
 push:
   branches:
     - 3ds-main
 pull_request:
   branches:
     - 3ds-main
     
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Enviornment
        run: |
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          
      - name: Install Dependencies
        run: sudo dkp-pacman -S 3ds-libtheora 3ds-sdl libctru 3ds-dev
        
      - name: Build ELF and 3DSX
        run: |
          git clone https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation
          rm Game
          cd Sonic-Mania-Decompilation
          mv SonicMania ../RSDKv5-Decompilation/Game
          cd ..
          rm -rf Sonic-Mania-Decompilation
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=$DEVKITPRO/devkitARM
          make PLATFORM=3DS
          echo Build done.   
          
      - name: Package CIA
        run: |
          cd 3ds
          chmod +x bannertool
          chmod +x makerom
          sudo ./build_cia.sh
          
      # Setup artifact folder
      - name: Setup artifact folder
        run: |
          mkdir artifacts
          cp bin/3DS/CTR/SonicMania.cia artifacts/
  
      # Publish Artifacts
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: sonicmania-cia
          path: artifacts
